# Generated by Django 5.0.2 on 2025-04-12 02:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectsite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgmembers',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='student',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
